github_url = "https://github.com/TankerHQ/tsrc"

[version]
current = "2.2.0"
regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  (
    -
    (?P<channel>alpha|beta|r)
    (?P<release>\d+)
  )?
'''

[git]
tag_template = "v{new_version}"
message_template = "Bump to {new_version}"

[[file]]
src = "pyproject.toml"
search = 'version = "{current_version}"'


[[file]]
src = "tsrc/__init__.py"
search = "__version__ ="


[[before_push]]
name = "Check Changelog"
cmd = "grep -q {new_version} docs/changelog.md"

[[after_push]]
name = "Publish project on Pypi"
cmd = "./publish.sh"
