name: linters

on:
  push:
    branches: [master]
    tags: v*
  pull_request:

jobs:
  run_linters:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v1

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Prepare project for development
      run: |
        python -m pip install poetry
        python -m poetry install

    - name: Run linters
      run: ./lint.sh
